### ISSUE TITLE
Strongly typed models

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/DD4T.Core#1]

**Comment by Ei8htSe7en** [comment]
First pull request for DD4T.ViewModels has been submitted

**Comment by quirijnslings** [comment]
I have tested the ViewModels, and have a few findings to share. Please comment!

# Multimedia
I could not get Multimedia link fields to work. Can you give me an example of how to use this?

# Multivalue
I get an error when using a field of type List<…>. Can you give an example of how to use a multi-value field (string, Keyword, anything).

# ComponentPresentationsAttribute
We need a ComponentPresentationsAttribute (not abstract!) because in many cases customers have pages with only one region of CPs. So we could do this in our Page models:

```
[ComponentPresentations]
IList<object> AllComponentPresentations
```

# PageTitleAttribute
I’m missing a PageTitleAttribute (there is a ComponentTitleAttribute)

# Access to DataModel
This is probably the biggest problem. We need access to the data model to render CPs, but also for XPM and SmartTarget. Right now we don’t have the information to handle this. I suggest that we make the DataModel property public and visible. It is just some extra information, I don’t think it is a problem if we leave it in, and it makes our lives way easier.

# Rendering CPs
Related to this: even if we have the DataModel (= ComponentPresentation or Page) on the entity, how will we render the entity? RenderPartial works, but it looks for the views in the ~/Views/Page folder, which is a bit confusing. Also, we need to have the ComponentController level because you can create custom Controllers and Actions as well (using DD4T as a ‘portal light’). 
So: we should have something similar to the old DefaultComponentPresentationRenderer, but without all the ‘filter by view / schema’ stuff.

**Comment by quirijnslings** [comment]
Sia and I fixed the multimedia. It is now more consistent (we think). You can map to the current component's multimedia property, or to the multimedia property of a linked mm component. The latter is not strictly necessary but may be a useful shortcut in some cases.

While we fixed this, we also made it possible to omit the list of expected types from the LinkedComponentAttribute declaration. The attribute is now able to read this information from the type of the property in the model class. So this will now work:

[LinkedComponentField]
public NewsArticle NewsArticle { get; set; }

We still need to apply the same logic to KeywordFieldAttribute and EmbeddedFieldAttribute. 

The error with lists occurred because I was using IList, apparently you need to use the implementation instead of the interface.
Rendering is now possible by adding RenderData to the model (there is an attribute for that). The RenderData contains the information needed to render the model.

The PageTitleAttribute and ComponentPresentationsAttribute are still missing but we can easily add them later.

**Comment by Ei8htSe7en** [comment]
Just seeing this all now . . .

Regarding multivalue stuff &mdash; last I remember, it will only work for properties, not fields. And as you discovered, you need to use concrete implementations that have a parameterless constructor. This is actually a rather large overall constraint (by default): **all properties marked with model attributes must be concrete and have parameterless constructors**. I guarantee that will be a pain point for many, **but** users actually have the options to implement their own `IViewModelResolver`, specifically the `object ResolveInstance(Type type);` method. 

In fact, there should really be an `IDependencyResolver` interface just like .NET MVC that _only_ handles Type resolving. Currently the `IViewModelResolver` violates the single responsibility principle as its handling resolving View Models, Model Properties, _and_ reflection related tasks. Clearly its doing too many different things.

Good thinking on the multimedia &mdash; I believe my original implementation was very specific to my use case at the time.

Also glad to hear that the list of Types is no longer required in the linked component field. I was on my way there when I stopped development, since of course the Types can totally be inferred.

Regarding the access to the Data Model &mdash; not sure I follow as I'm pretty certain that all `IViewModel` objects had a `ModelData` property that contain all the underlying Tridion data, no? Sounds like you got it worked out with the `RenderData` concept though. 

I'm gonna jump back into the code now and see if I can quickly get those two attributes finished. Now I get to do one of the most painful things: go back and read code that I wrote but try not to re-write it all!

**Comment by Ei8htSe7en** [comment]
Hey where is that multimedia code you mentioned? The multimedia attributes still look the same as my original code and I can't find any commits about it specifically.

**Comment by quirijnslings** [comment]
Created some additional issues around this topic, but the main issue can be closed because it is working.
